playbook:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 1.0.0    
  service:
    name: "playbook"
    annotations:
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: external-ingress
        ingress.kubernetes.io/force-ssl-redirect: true
        certmanager.k8s.io/cluster-issuer: letsencrypt-production
        forecastle.stakater.com/appName: Playbook
        forecastle.stakater.com/expose: true
        forecastle.stakater.com/icon: https://raw.githubusercontent.com/stakater/ForecastleIcons/master/playbook.png
      config.xposer.stakater.com/IngressURLTemplate: "{{ `{{.Service}}.{{.Domain}}` }}"
      config.xposer.stakater.com/Domain: stakater.com
      config.xposer.stakater.com/TLS: "true"
    labels:
      expose: 'true'
  deployment:
    tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule"
    replicas: 1
    podLabels:      
      app: playbook
    containerName: playbook
    imagePullSecrets: docker-registry-secret
    image:
      name: stakater/playbook
      tag: 1.0.0

